repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.2.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
