# THis file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  organization: "{{ cookiecutter.organization }}"
  license: "{{ cookiecutter.license }}"
  version: "{{ cookiecutter.version }}"
  github_name: "{{ cookiecutter.github_name }}"
  email: "{{ cookiecutter.email }}"
